__maven_unleash.yml: Add Maven version check for -ntp commandline option availability

diff --git a/.github/workflows/__maven_unleash.yml b/.github/workflows/__maven_unleash.yml
--- a/.github/workflows/__maven_unleash.yml
+++ b/.github/workflows/__maven_unleash.yml
@@ -149,6 +149,38 @@ jobs:
         with:
           maven-version: '${{ inputs.mavenVersion }}'
 
+      - name: Determine Maven version related cmd options
+        id: maven-cmd-options
+        run: |
+          # Helper function to convert semver version to int value for comparison
+          # Convert an up to 4 digit semversion i.j.k.l with up to 3 digits each part to
+          # an integer value.
+          #
+          # Inspired by: https://stackoverflow.com/a/37939589/15763374
+          #
+          # Usage:
+          #   if [ $(semver2int $VAR) -ge $(semver2int "6.2.0") ]; then
+          #     echo "Version is up to date"
+          #   fi
+          #
+          semver2int() {
+            if [[ -n "$1" && ! "$1" =~ ^[0-9]+(\.[0-9]{1,3}){0,3}$ ]]; then
+              echo "##### $0: '$1' is an invalid version for this script! It must be up to 4 numeric parts separated by '.' and up to 3 digits for each part!" >&2
+              exit 1
+            fi
+            echo "$1" | awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }'
+          }
+          EFFECTIVE_MAVEN_VERSION="$(mvn -q -v)"
+          echo "Effective installed Maven version: ${EFFECTIVE_MAVEN_VERSION}"
+          if [[ $(semver2int "${EFFECTIVE_MAVEN_VERSION}") -ge $(semver2int "3.6.1") ]]; then
+            MVN_NTP_OPTION="-ntp"
+            echo "  => -ntp commandline option is available!"
+          else
+            MVN_NTP_OPTION=""
+            echo "  => -ntp commandline option is NOT available!"
+          fi
+          echo "MVN_NTP_OPTION=${MVN_NTP_OPTION}" >> $GITHUB_ENV
+
       - name: Create Maven settings.xml
         id: create-maven-settings
         uses: mavenplugins/actions-maven-settings-action@vHEAD
@@ -185,7 +217,7 @@ jobs:
 
       - name: Validate Maven running properly with project POM
         run: |
-          mvn -ntp -B -Dexpression=project.version -DforceStdout help:evaluate
+          mvn ${{ env.MVN_NTP_OPTION }} -B -Dexpression=project.version -DforceStdout help:evaluate
 
       - name: Set environment for project, compile and toolchain version
         run: |
@@ -303,7 +335,7 @@ jobs:
           # -U   Forces a check for missing releases and updated snapshots on
           # -e   Extended error logging
           #
-          mvn -ntp -B -U -e \
+          mvn ${{ env.MVN_NTP_OPTION }} -B -U -e \
               ${UNLEASH_CMDLINE_GOAL} \
                 -DenableLogTimestamps=true \
                 -Dunleash.releaseVersion=${{ env.EFFECTIVE_RELEASE_VERSION }} \
